name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:

    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        exempt-issue-labels: 'pinned,security'
        exempt-pr-labels: 'pinned,security'
        stale-issue-message: 'This issue has been marked inactive and will be closed if no further activity occurs.'
        stale-pr-message: 'This pr has been marked inactive and will be closed if no further activity occurs.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
